name: UPM Sync
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      base: https://dl.google.com/games/registry/unity/com.google.firebase.app/com.google.firebase.app
      version: 8.0.0
    steps:
      - uses: actions/checkout@v2
      - name: Config
        run: |
          git config --local user.email "contact@gameworkstore.com"
          git config --local user.name "game-workstore-bot"
      
      - name: Download Package
        run: |
          rm -rf Staging
          mkdir Staging
          cd Staging
          curl ${{ env.base }}-${{ env.version }}.tgz --output content.tgz
          tar -xvzf content.tgz
          rm content.tgz
          ls
      
      - name: Zip Staging/package/Firebase/Plugins/x86_64/FirebaseCppApp-8_0_0.so
        run: |
          File=./Staging/package/Firebase/Plugins/x86_64/FirebaseCppApp-8_0_0.so
          #MaxSize = 100 MB
          MaxSize=100000000 
          FileSize=$(stat -c%s "$File")
          echo "Size of $File = $FileSize bytes."
          if (( FileSize > MaxSize )); then
              Zipped=./Staging/package/Firebase/Plugins/x86_64/FirebaseCppApp-8_0_0.so.zip
              zip $Zipped $File
              FileSize=$(stat -c%s "$Zipped")
              echo "$Zipped were zipped. $Zipped = $FileSize bytes."
              rm -rf $File
          fi
      
      - name: Commit
        run: |
          git add --a
          git commit -m "Package Update ${{ env.version }}"
          git push origin

      - name: Update README
        if: false
        run: |
          if ! cmp --silent "README.md" "Assets/Package/README.md"; then
              echo "different"
              cp -f README.md Assets/Package/README.md
              git add --a
              git commit -m "Updated README.md"
              git push origin
          fi

      - name: Cook UPM
        run: |
          ls Staging/package/
          git subtree split -P Staging/package/ -b upm
          git checkout upm
          ls

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: upm
          force: true
